### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by Moki0** [TabooLib/adyeshach#1]
/npc modify 指令把 Visible Distance 设置为 任意数值会出现一下报错

`[20:15:03 INFO]: MokierTea issued server command: /adyeshachapi edit meta 9d0db76efe9048f6afcb7c5367dedc83 visibleDistance
[20:15:06 WARN]: java.lang.RuntimeException: Metadata "visibleDistance" not allowed.
[20:15:06 WARN]:        at ink.ptms.adyeshach.common.entity.EntityMetaable.setMetadata(EntityMetaable.kt:89)
[20:15:06 WARN]:        at ink.ptms.adyeshach.common.editor.Editors$TEXT$1$1.accept(Editors.kt:38)
[20:15:06 WARN]:        at ink.ptms.adyeshach.common.editor.Editors$TEXT$1$1.accept(Editors.kt:25)
[20:15:06 WARN]:        at io.izzel.taboolib.util.lite.Signs.lambda$onPacket$0(Signs.java:83)
[20:15:06 WARN]:        at io.izzel.taboolib.common.plugin.InternalPlugin.lambda$runTask$0(InternalPlugin.java:144)
[20:15:06 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[20:15:06 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[20:15:06 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[20:15:06 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[20:15:06 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[20:15:06 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[20:15:06 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by Bkm016** [comment]
Fixed
