### ISSUE TITLE
bug反馈 皮肤问题 1.3.18

### ISSUE THREAD

**Issue by QQ464944870** [TabooLib/Adyeshach#14]
报错
[13:29:08 WARN]: java.io.FileNotFoundException: plugins\Adyeshach\skin\girl (系统找不到指定的路径。)
[13:29:08 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[13:29:08 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
[13:29:08 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
[13:29:08 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[13:29:08 WARN]:        at kotlin1510.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
[13:29:08 WARN]:        at kotlin1510.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
[13:29:08 WARN]:        at kotlin1510.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134)
[13:29:08 WARN]:        at ink.ptms.adyeshach.common.util.mojang.MojangAPI.get(MojangAPI.kt:61)
[13:29:08 WARN]:        at ink.ptms.adyeshach.common.entity.type.AdyHuman$setTexture$1.invoke(AdyHuman.kt:193)
[13:29:08 WARN]:        at ink.ptms.adyeshach.common.entity.type.AdyHuman$setTexture$1.invoke(AdyHuman.kt:191)
[13:29:08 WARN]:        at ink.ptms.adyeshach.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89)
[13:29:08 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:29:08 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[13:29:08 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:29:08 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[13:29:08 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[13:29:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Bkm016** [comment]
Fixed
