### ISSUE TITLE
[BUG报错] 在砍MM怪的时候出现的

### ISSUE THREAD

**Issue by 849025143** [TabooLib/Adyeshach#20]
[00:10:26 ERROR]: Could not pass event PlayerInteractEvent to Adyeshach v1.4.6
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at ink.ptms.adyeshach.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
        at ink.ptms.adyeshach.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
        at ink.ptms.adyeshach.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at ink.ptms.adyeshach.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at ink.ptms.adyeshach.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:512) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2223) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:29) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:8) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance between yc and world
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.5.jar:git-Paper-790]
        at ink.ptms.adyeshach.internal.listener.ListenerModelEngine.e$lambda-0(ListenerModelEngine.kt:48) ~[?:?]
        at ink.ptms.adyeshach.api.AdyeshachAPI.getEntities(AdyeshachAPI.kt:205) ~[?:?]
        at ink.ptms.adyeshach.internal.listener.ListenerModelEngine.e(ListenerModelEngine.kt:48) ~[?:?]
        ... 30 more

**Comment by 849025143** [comment]
trmenu 也无法使用物品打开 菜单

**Comment by Bkm016** [comment]
已在最新版解决
