### ISSUE TITLE
Model-Engine-R3.0.1 报错

### ISSUE THREAD

**Issue by Iseason2000** [TabooLib/adyeshach#53]
~~~ log
[15:34:46 WARN]: [Adyeshach] Task #173 for Adyeshach v1.5.13-op14 generated an exception
java.lang.NoSuchMethodError: 'com.ticxo.modelengine.api.manager.ModelManager com.ticxo.modelengine.api.ModelEngineAPI.getModelManager()'
        at ink.ptms.adyeshach.common.entity.EntityInstance.showModelEngine(EntityInstance.kt:839) ~[Adyeshach-1.5.13-op14.jar:?]
        at ink.ptms.adyeshach.common.entity.EntityInstance.spawn(EntityInstance.kt:175) ~[Adyeshach-1.5.13-op14.jar:?]
        at ink.ptms.adyeshach.common.entity.type.AdyEntityLiving.visible(AdyEntityLiving.kt:62) ~[Adyeshach-1.5.13-op14.jar:?]
        at ink.ptms.adyeshach.common.entity.EntityInstance.onTick(EntityInstance.kt:781) ~[Adyeshach-1.5.13-op14.jar:?]
        at ink.ptms.adyeshach.common.entity.manager.Manager.onTick(Manager.kt:120) ~[Adyeshach-1.5.13-op14.jar:?]
        at ink.ptms.adyeshach.common.entity.manager.ManagerEvents$onTick$1.invoke(ManagerEvents.kt:55) ~[Adyeshach-1.5.13-op14.jar:?]
        at ink.ptms.adyeshach.common.entity.manager.ManagerEvents$onTick$1.invoke(ManagerEvents.kt:54) ~[Adyeshach-1.5.13-op14.jar:?]
        at ink.ptms.adyeshach.taboolib.platform.BukkitExecutor$submit$3.run(BukkitExecutor.kt:60) ~[Adyeshach-1.5.13-op14.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1809]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1809]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1809]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1809]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1809]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1809]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1809]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
~~~

一直刷这个，看了一下 Model-Engine 的 API 较 2.5.2 改动挺大的

**Comment by Bkm016** [comment]
暂不考虑支持me3
