### ISSUE TITLE
关于ServerTours未找到类错误

### ISSUE THREAD

**Issue by inrhor** [TabooLib/adyeshach#59]
ServerTours版本：2.0.3
Ady版本：2.0快照3
`[21:48:37] [Server thread/WARN]: [Adyeshach] Task #1710 for Adyeshach v2.0.0-snapshot-3 generated an exception
java.lang.NoClassDefFoundError: tech/mistermel/servertours/api/ServerToursAPI
	at ink.ptms.adyeshach.impl.ServerTours.isRoutePlaying(ServerTours.kt:12) ~[adyeshach-2.0.0-snapshot-3.jar:?]
	at ink.ptms.adyeshach.impl.entity.DefaultEntityExtensionsKt.handleTracker(DefaultEntityExtensions.kt:95) ~[adyeshach-2.0.0-snapshot-3.jar:?]
	at ink.ptms.adyeshach.impl.entity.DefaultEntityInstance.onTick(DefaultEntityInstance.kt:413) ~[adyeshach-2.0.0-snapshot-3.jar:?]
	at ink.ptms.adyeshach.impl.manager.DefaultManager.onTick(DefaultManager.kt:75) ~[adyeshach-2.0.0-snapshot-3.jar:?]
	at ink.ptms.adyeshach.impl.manager.DefaultManagerHandler.onActive$lambda-1(DefaultManagerHandler.kt:29) ~[adyeshach-2.0.0-snapshot-3.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: tech.mistermel.servertours.api.ServerToursAPI
	... 13 more`

**Comment by inrhor** [comment]
Fixed
