### ISSUE TITLE
[Closed] 玩家从Bungeecord/Waterfall服务端 连接到 有Adyeshach插件的子服 会断开连接

### ISSUE THREAD

**Issue by 3154311518** [TabooLib/adyeshach#70]
玩家从Bungeecord/Waterfall服务端 连接到 有Adyeshach插件的子服 会断开连接
直接连接不通过Bungeecord/Waterfall就不会断开连接

子服没有任何报错,BungeeCord报错

00:50:53 [信息] [Loong715,/127.0.0.1:59044] <-> InitialHandler has connected
00:50:53 [信息] [Loong715] <-> ServerConnector [login] has connected
00:50:57 [严重] [Loong715] <-> DownstreamBridge <-> [login] - encountered exception
java.lang.IllegalArgumentException: Team ady_1015 already exists in this scoreboard
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
    at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:224)
    at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Thread.java:855)
00:50:57 [信息] [Loong715] disconnected with: IllegalArgumentException : Team ady_1015 already exists in this scoreboard @ com.goo
gle.common.base.Preconditions:220
00:50:57 [信息] [Loong715] -> UpstreamBridge has disconnected
00:50:57 [信息] [Loong715] <-> DownstreamBridge <-> [login] has disconnected

**Comment by 3154311518** [comment]
Bungeecord/Waterfall最新版本
后端spigot1.12.2/paper1.12.2

**Comment by Bkm016** [comment]
https://github.com/TabooLib/adyeshach/commit/0985d594b5f79426af5867fcf6e74da76adc5b50

**Comment by Bkm016** [comment]
不同子服不同id
