### ISSUE TITLE
1.18.2在创建NPC后NPC未出现

### ISSUE THREAD

**Issue by Zxblll843192** [TabooLib/adyeshach#74]
DownWinter issued server command: /ady
[21:07:40 INFO]: DownWinter issued server command: /ady create PLAYER teacher1
[21:07:40 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.network.PlayerConnection#sendPacket(net.minecraft.network.protocol.game.PacketPlayOutPlayerInfo)
[21:07:40 WARN]: 	at adyeshach-2.0.0-snapshot-32.jar//ink.ptms.adyeshach.taboolib.library.reflex.JavaClassStructure.getMethod(JavaClassStructure.kt:25)
[21:07:40 WARN]: 	at adyeshach-2.0.0-snapshot-32.jar//ink.ptms.adyeshach.taboolib.library.reflex.ReflexClass.getMethod(ReflexClass.kt:42)
[21:07:40 WARN]: 	at adyeshach-2.0.0-snapshot-32.jar//ink.ptms.adyeshach.taboolib.module.nms.PacketSender.sendPacket(PacketSender.kt:41)
[21:07:40 WARN]: 	at adyeshach-2.0.0-snapshot-32.jar//ink.ptms.adyeshach.taboolib.module.nms.MinecraftServerUtilKt.sendPacketBlocking(MinecraftServerUtil.kt:162)
[21:07:40 WARN]: 	at adyeshach-2.0.0-snapshot-32.jar//ink.ptms.adyeshach.taboolib.module.nms.MinecraftServerUtilKt.sendPacket$lambda-5(MinecraftServerUtil.kt:130)
[21:07:40 WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:07:40 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:07:40 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:07:40 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:07:40 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Zxblll843192** [comment]
补充：运行环境为1.18.2的purpur服务端
