### ISSUE TITLE
[报错] 1.20.4版本运行当前源代码构建出的adyes产生如下报错

### ISSUE THREAD

**Issue by xiaozhangup** [TabooLib/adyeshach#79]
`
[21:45:23] [Server thread/ERROR]: Could not pass event AdyeshachEntityVisibleEvent to Adyeshach v2.0.0-snapshot-36
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.nbt.IntArrayTag$1.readAccounted(IntArrayTag.java:28) ~[?:?]
	at net.minecraft.nbt.IntArrayTag$1.load(IntArrayTag.java:17) ~[?:?]
	at net.minecraft.nbt.IntArrayTag$1.c(IntArrayTag.java:14) ~[?:?]
	at net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:382) ~[?:?]
	at net.minecraft.nbt.NbtIo.readAnyTag(NbtIo.java:347) ~[?:?]
	at net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:632) ~[?:?]
	at net.minecraft.network.FriendlyByteBuf.readWithCodec(FriendlyByteBuf.java:113) ~[?:?]
	at net.minecraft.network.FriendlyByteBuf.readWithCodecTrusted(FriendlyByteBuf.java:107) ~[?:?]
	at net.minecraft.network.FriendlyByteBuf.readComponentTrusted(FriendlyByteBuf.java:534) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetPlayerTeamPacket$Parameters.<init>(ClientboundSetPlayerTeamPacket.java:161) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetPlayerTeamPacket.<init>(ClientboundSetPlayerTeamPacket.java:55) ~[?:?]
	at ink.ptms.adyeshach.impl.nms.DefaultMinecraftScoreboardOperator.updateTeam(DefaultMinecraftScoreboardOperator.kt:76) ~[?:?]
	at ink.ptms.adyeshach.core.MinecraftScoreboardOperator.updateTeam(MinecraftScoreboardOperator.kt:24) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.impl.VisualTeam$PlayerTeam.join(VisualTeam.kt:82) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.impl.VisualTeam.onVisible(VisualTeam.kt:51) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at ink.ptms.adyeshach.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2124]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at ink.ptms.adyeshach.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:40) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.impl.entity.DefaultEntityInstance.prepareSpawn(DefaultEntityInstance.kt:287) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.impl.entity.type.DefaultEntityLiving.visible(DefaultEntityLiving.kt:38) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.impl.entity.DefaultEntityExtensionsKt.handleTracker(DefaultEntityExtensions.kt:91) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.impl.entity.DefaultEntityInstance.onTick(DefaultEntityInstance.kt:440) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.impl.manager.DefaultManager.onTick(DefaultManager.kt:75) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at ink.ptms.adyeshach.impl.manager.DefaultManagerHandler.onActive$lambda-1(DefaultManagerHandler.kt:29) ~[adyeshach-2.0.0-snapshot-36.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1666) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1545) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
`

**Comment by Bkm016** [comment]
这个功能坏了，不会修。

---

解决办法： `config.yml` 禁用 `team-id` 节点。

```yaml
Settings:
  ...
  team-id: DISABLED
```

**Comment by xiaozhangup** [comment]
> 这个功能坏了，不会修。
> 
> 解决办法： `config.yml` 禁用 `team-id` 节点。
> 
> ```yaml
> Settings:
>   ...
>   team-id: DISABLED
> ```

会有什么影响吗？
