### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Yurium7** [TabooLib/adyeshach#82]
Purpur 1.19.4 - 1985核心下 加载Ady 2.0.1出现如下报错

[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Relocating ...
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Relocating ...
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Relocating ...
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Relocating ...
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Relocating ...
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Relocating ...
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib-common:1.8.22
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib:1.8.22
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Loading library org.jetbrains:annotations:13.0
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Loading library org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.3
[18:28:33 INFO]: [Adyeshach-2.0.1.jar] Relocating ...
[18:28:33 ERROR]: [Adyeshach-2.0.1.jar] [TabooLib] Failed to initialize primitive loader, the plugin "Adyeshach-2.0.1.jar" will be disabled!
[18:28:33 WARN]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[18:28:33 WARN]:        at Adyeshach-2.0.1.jar//ink.ptms.adyeshach.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:30)
[18:28:33 WARN]:        at Adyeshach-2.0.1.jar//ink.ptms.adyeshach.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:44)
[18:28:33 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[18:28:33 WARN]:        at java.base/java.lang.Class.forName(Class.java:467)
[18:28:33 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78)
[18:28:33 WARN]:        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123)
[18:28:33 WARN]:        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35)
[18:28:33 WARN]:        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116)
[18:28:33 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[18:28:33 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[18:28:33 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445)
[18:28:33 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
[18:28:33 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1120)
[18:28:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[18:28:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[18:28:33 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[18:28:33 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:28:33 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:28:33 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:28:33 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:28:33 WARN]:        at Adyeshach-2.0.1.jar//ink.ptms.adyeshach.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:28)
[18:28:33 WARN]:        ... 14 more
[18:28:33 WARN]: Caused by: java.lang.NoClassDefFoundError: ink/ptms/adyeshach/taboolib/common/platform/Plugin
[18:28:33 WARN]:        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[18:28:33 WARN]:        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
[18:28:33 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2673)
[18:28:33 WARN]:        at ink.ptms.adyeshach.taboolib.common.PrimitiveLoader.loadFile(PrimitiveLoader.java:200)
[18:28:33 WARN]:        at ink.ptms.adyeshach.taboolib.common.PrimitiveLoader.load(PrimitiveLoader.java:131)
[18:28:33 WARN]:        at ink.ptms.adyeshach.taboolib.common.PrimitiveLoader.loadAll(PrimitiveLoader.java:143)
[18:28:33 WARN]:        at ink.ptms.adyeshach.taboolib.common.PrimitiveLoader.init(PrimitiveLoader.java:92)
[18:28:33 WARN]:        ... 19 more
[18:28:33 WARN]: Caused by: java.lang.ClassNotFoundException: ink.ptms.adyeshach.taboolib.common.platform.Plugin
[18:28:33 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185)
[18:28:33 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152)
[18:28:33 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[18:28:33 WARN]:        ... 26 more
[18:28:33 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'Adyeshach-2.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: ink/ptms/adyeshach/taboolib/common/platform/Plugin
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: ink/ptms/adyeshach/taboolib/common/platform/Plugin
        at ink.ptms.adyeshach.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:56) ~[Adyeshach-2.0.1.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.19.4.jar:git-Purpur-1985]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: ink.ptms.adyeshach.taboolib.common.platform.Plugin
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at ink.ptms.adyeshach.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:56) ~[Adyeshach-2.0.1.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.19.4.jar:git-Purpur-1985]
        ... 9 more

**Comment by Bkm016** [comment]
回退版本
