### ISSUE TITLE
[BUG] NPC消失问题

### ISSUE THREAD

**Issue by ayide01** [TabooLib/adyeshach#86]
插件版本：2.0.14
服务端版本：mohist-1.16.5-174

重启服务器后创建的NPC会消失

报错如下：
[13:25:23 WARN]: [Adyeshach] Unable to check chunk visibility. Please report this issue to the developer.
[13:25:23 WARN]: java.lang.IllegalAccessError: class ink.ptms.adyeshach.impl.nms.DefaultMinecraftHelper tried to access private field net.minecraft.world.server.ServerWorld.field_241102_C_ (ink.ptms.adyeshach.impl.nms.DefaultMinecraftHelper is in unnamed module of loader ink.ptms.adyeshach.taboolib.module.nms.AsmClassLoader @476cb760; net.minecraft.world.server.ServerWorld is in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @786ff1cb)
[13:25:23 WARN]:        at ink.ptms.adyeshach.impl.nms.DefaultMinecraftHelper.isChunkVisible(DefaultMinecraftHelper.kt:176)
[13:25:23 WARN]:        at ink.ptms.adyeshach.impl.entity.DefaultEntityExtensionsKt.handleTracker(DefaultEntityExtensions.kt:88)
[13:25:23 WARN]:        at ink.ptms.adyeshach.impl.entity.DefaultEntityInstance.onTick(DefaultEntityInstance.kt:495)
[13:25:23 WARN]:        at ink.ptms.adyeshach.impl.manager.DefaultManager.onTick(DefaultManager.kt:75)
[13:25:23 WARN]:        at ink.ptms.adyeshach.impl.manager.DefaultManagerHandler$onActive$2.invoke(DefaultManagerHandler.kt:30)
[13:25:23 WARN]:        at ink.ptms.adyeshach.impl.manager.DefaultManagerHandler$onActive$2.invoke(DefaultManagerHandler.kt:29)
[13:25:23 WARN]:        at ink.ptms.adyeshach.taboolib.platform.BukkitExecutor$BukkitRunningTask$instance$1.run(BukkitExecutor.kt:87)
[13:25:23 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:90)
[13:25:23 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461)
[13:25:23 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1081)
[13:25:23 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:345)
[13:25:23 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1033)
[13:25:23 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:847)
[13:25:23 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267)
[13:25:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Bkm016** [comment]
暂不支持该平台
