### ISSUE TITLE
NPC消失了

### ISSUE THREAD

**Issue by 3269199948** [TabooLib/adyeshach#93]
[Adyeshach] Unable to check chunk visibility. Please report this issue to the developer.
[13:42:37 WARN]: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/CraftServer/CraftWorld
[13:42:37 WARN]:        at ink.ptms.adyeshach.impl.nms.DefaultMinecraftHelper.isChunkVisible(DefaultMinecraftHelper.kt:170)
[13:42:37 WARN]:        at Adyeshach-2.0.16.jar//ink.ptms.adyeshach.impl.entity.DefaultEntityExtensionsKt.handleTracker(DefaultEntityExtensions.kt:94)
[13:42:37 WARN]:        at Adyeshach-2.0.16.jar//ink.ptms.adyeshach.impl.entity.DefaultEntityInstance.onTick(DefaultEntityInstance.kt:497)
[13:42:37 WARN]:        at Adyeshach-2.0.16.jar//ink.ptms.adyeshach.impl.manager.DefaultManager.onTick(DefaultManager.kt:75)
[13:42:37 WARN]:        at Adyeshach-2.0.16.jar//ink.ptms.adyeshach.impl.manager.DefaultManagerHandler$onActive$2.invoke(DefaultManagerHandler.kt:30)
[13:42:37 WARN]:        at Adyeshach-2.0.16.jar//ink.ptms.adyeshach.impl.manager.DefaultManagerHandler$onActive$2.invoke(DefaultManagerHandler.kt:29)
[13:42:37 WARN]:        at Adyeshach-2.0.16.jar//ink.ptms.adyeshach.taboolib.platform.BukkitExecutor$BukkitRunningTask$instance$1.run(BukkitExecutor.kt:87)
[13:42:37 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[13:42:37 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[13:42:37 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699)
[13:42:37 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467)
[13:42:37 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571)
[13:42:37 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
[13:42:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[13:42:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[13:42:37 WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.CraftServer.CraftWorld
[13:42:37 WARN]:        ... 15 more

我使用Paper1.20.6和Adyeshach-2.0.16

**Comment by Bkm016** [comment]
暂不支持 1.20.5+
