### ISSUE TITLE
paper1.21.1报错，无法使用

### ISSUE THREAD

**Issue by NeglectDream** [TabooLib/adyeshach#97]
[19:52:16] [Server thread/WARN]: [Adyeshach] Unable to check chunk visibility. Please report this issue to the developer.
[19:52:16] [Server thread/WARN]: java.lang.NoSuchFieldError: Class net.minecraft.server.level.ChunkMap does not have member field 'it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap visibleChunkMap'
[19:52:16] [Server thread/WARN]: 	at ink.ptms.adyeshach.impl.nms.DefaultMinecraftHelper.isChunkVisible(DefaultMinecraftHelper.kt:171)
[19:52:16] [Server thread/WARN]: 	at [自定义NPC]Adyeshach.jar//ink.ptms.adyeshach.impl.entity.DefaultEntityExtensionsKt.handleTracker(DefaultEntityExtensions.kt:115)
[19:52:16] [Server thread/WARN]: 	at [自定义NPC]Adyeshach.jar//ink.ptms.adyeshach.impl.entity.DefaultEntityExtensionsKt.handleTracker(DefaultEntityExtensions.kt:99)
[19:52:16] [Server thread/WARN]: 	at [自定义NPC]Adyeshach.jar//ink.ptms.adyeshach.impl.entity.DefaultEntityInstance.onTick(DefaultEntityInstance.kt:502)
[19:52:16] [Server thread/WARN]: 	at [自定义NPC]Adyeshach.jar//ink.ptms.adyeshach.impl.manager.DefaultManager.onTick(DefaultManager.kt:75)
[19:52:16] [Server thread/WARN]: 	at [自定义NPC]Adyeshach.jar//ink.ptms.adyeshach.impl.manager.DefaultManagerHandler$onActive$2.invoke(DefaultManagerHandler.kt:36)
[19:52:16] [Server thread/WARN]: 	at [自定义NPC]Adyeshach.jar//ink.ptms.adyeshach.impl.manager.DefaultManagerHandler$onActive$2.invoke(DefaultManagerHandler.kt:34)
[19:52:16] [Server thread/WARN]: 	at [自定义NPC]Adyeshach.jar//ink.ptms.adyeshach.taboolib.platform.BukkitExecutor$BukkitRunningTask$instance$1.run(BukkitExecutor.kt:91)
[19:52:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
[19:52:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474)
[19:52:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1756)
[19:52:16] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:521)
[19:52:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1638)
[19:52:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1325)
[19:52:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)

**Comment by hotic** [comment]
ady 暂不支持 1.21
